---
title: "Covid91 vaccine study Final2022"
author: "Riley Wheeler"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "Summer 2022" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final_Data.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid91) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

$H_0$ = The effectiveness of the vaccine does not differ between any of the subgroups.

$H_A$ = There is a difference in the vaccine's effectiveness between the four subgroups.



## Males

$H_0$ = The effectiveness of the vaccine does not differ between any of the subgroups.

$H_A$ = There is a difference in the vaccine's effectiveness between the four subgroups.

## Methods

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferrential Results

### Male Conclusion



## Females



## Methods

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferrential Results

### Male Conclusion



## LGBTQ

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferrential Results

### Male Conclusion



## Druggies

### Graphical Descriptive Results

### Numerical Descriptive Results

### Inferrential Results

### Male Conclusion

## Final Discussion and Conclusion

